#!/usr/bin/env bash

git submodule update --init --recursive.
git config diff.submodule log
git config status.submodulesummary true
git config submodule.recurse true
git config push.recurseSubmodules on-demand

git pull --recurse-submodules
